version: '3.7'

services:
  api_observasampa:
    build:
      context: ./api_observasampa
    container_name: api_observasampa
    image: api_observasampa
    environment:
      ENV: ${ENV}
    env_file: .env
    restart: unless-stopped
    networks:
      - api_observa_network
    ports:
      - "8000:8000"  # Expõe a porta 8000 para o Railway

networks:
  api_observa_network:
    driver: bridge
    name: api_observa_network
